spring.application.name=VolyVary

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/volyvary_db
spring.datasource.username=postgres
spring.datasource.password=POSTGRES
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate : Met à jour les tables automatiquement (pratique en développement)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true