DROP TABLE IF EXISTS mouvement_projet;
DROP TABLE IF EXISTS projet;
DROP TABLE IF EXISTS utilisateur;

CREATE TABLE utilisateur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL UNIQUE,
    mdp VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE projet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(150) NOT NULL,
    description VARCHAR(255),
    utilisateur_id BIGINT NOT NULL,
    CONSTRAINT fk_projet_utilisateur
        FOREIGN KEY (utilisateur_id)
        REFERENCES utilisateur (id)
        ON DELETE CASCADE
);

CREATE TABLE mouvement_projet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projet_id BIGINT NOT NULL,
    date_operation DATE NOT NULL,
    montant NUMERIC(14, 2) NOT NULL,
    nature VARCHAR(20) NOT NULL,
    libelle VARCHAR(255) NOT NULL,
    CONSTRAINT fk_mouvement_projet
        FOREIGN KEY (projet_id)
        REFERENCES projet (id)
        ON DELETE CASCADE
);
